sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        xgRCQoC62iQPd2ZhyHyk4EY2dW4FHfoX4xNa8+2uXF+PuIDQqkVuo6mHgvPSj4KEp0r24bjtw891RjtW9KPAGtuk8jGVDHRz/xfW1jq6JHUuLdcx9ZIpPN/0JU1sgtF7SY64IGo5p+qfUi8jL3J+UwUVKEV5nYXa3v3b9Aue6/RB5slemVifnP+XNYsjkx2VTr8PfG7fWpzpsraFQiaEh2qFYllZ3Thvspuad0/3mjoT0ZefBHBY8JUW/SoTqDOrZQZF1AbC4Q/GND47za/QNZfuzKBk/eD74++T2Ec5M1o9SnHk6sOf/ymNshlxEkcUHoXQi7S7fDdiIGNBWYIpywEyzZr6ZrDf9cQHiegAUuFD50jc4+3xN4TxeFSfNCa1lz/lne8/yOOaB9mnWex17Dp8VbCh1g+m+7cmxJK09N0wELGcezVVxZ3tWkYpMXykIOLeeEqvvoOmtbEsZQ4yh46HofvN3vtpSJGTUbpBUnjoftmYU77R42w3+0gUQeECxU8A4f0j7ng6qZWGoztkVLpqUyaiOXh8WjG0Ske3TJ0sC91Fxuf7l14mU28oBmUUzJUdqCPdqqCze6Y+b8fq+xjqbLZe3lAztNmAZyrSnEG4XxivJx4vsbotQVMRId9gQ5+GiTC9SvCGcBs2/FuYqJrcMyNE0W+G5chz2zjr9j8=
    - secure: >-
        jeAkwIpB2EMTsTZTkeu0Efc6YOu+a3hZqSGBCxK8d55urORJh0iNzfFMCejAdvYA1hNCxQFWu+Pw1fXRfmPLM0EPHMik/iDbXVqlBkbB7vhmIPudaRj/xzU/WjATYI0lRErh4qZk5mKV8eHWukfX0wGDr3KNBfTOo1WtLYyo2191pcE5LAZeYxHI7qIHA5LOtdd2p4J6ZIvcfh08vdf1h7wTrddwDiRR2MNUkecS/ToZ6r1KWtaHLr6ALcLF4AZ7Xcdivscl9N1ClPpZB+eNKSKa97WQf8idRFvnb3WnWY39pK+NxurK4kjYblWR6+p+600NCkQhZc9jAo8/WkKfOCjMuOG+I4HWxZcfr5TFzcpWbVAqNXq2tmoHpAtBV5CjaoWPhvT7ROU5R6GejRzLvTM0MSwZfxsDGInmYkOFcEd8Sae1D7NLrHlhMIhZXHkodP+PC4HGTqKCjx6cA/mku2EKSf1faQzHNlIk0RK2F+R/zttAScnno4ZpeqFvv9f9xrJ5k4SRsr3Llln/qz0ZK+EBVfMwGWtofIWAWPdW8V877Og8b5F+bX2nRYbj4ynCEr6frlGYp+605E2y1vBbEJtjKbEUSEOaC8wCZ2JDi5RnO+DlH6vENGPbXbEnKEHJhEqBNheIhXf6v1ZnbfrZQDqK9A4j0NF3CIOYtx5xJps=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
