sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        LFFo4JOR7KDpHJhib6XQxcEBCppRUGvCwbUoVyXuiavKDhdzVvhn3UHh6lqN/btYqEv+O5h25kZ/oiAvXybCexCgNKgii5j5Gq8bYx9fgGd9fr71BmyqCZTjZdNofRFwOgJ2My++8d1TfRFDGVdqBDWUyKnI9BubpnsmJBzQja3YVlx1f+3ubF16LDkza3gMme9bxR59NixuLr8JoR0UyFiVo8DyaBN+Pgrf2D7LVlwXnqJKTIEV+di9X7DSCHsSgZ+e3stPRCT3zbLXHqXYBxlnXmrpkXgqd9Ts4X8AzTFeUEhndOVoYV8nvIwJfKYZIwYbS8tmtgxSKCDHEbssjVms08JhBnJZrI8UQbG7typiL6sg3jWHxM9G434PjS3Pt86ghiLiIFSWRhEn/ykrZE9a5loeREmBiLSUppYrBaOdw0Bv3ZdTFGpIwWHw7TWuY4qoGZpKYk/mLGEut2bLsvp1wQPBeeeaknr0g34ZhBIFnc+LGMqTFsjmcUtR7VpEn0chZD7eetRQnI581Qb2zHDRen6A14NowKyv0JxJ+IiHJdkLQnaNcK+ozjeSXcJVF5sOxXZastLU5tZaI4Hp7LpE6tzDBx13T957rc2j41C7As2104B/KltiaNh/S2RoH9aMWc0RmovH5NT1qhUTu3FrJ+eZY3VgwNhp6IeWhqE=
    - secure: >-
        wY8DPwtJ3IzUJmWnmzgBVWIGVIyPBRKn0IoBayOk8X+NqfL6q53oEaUtf3+k18mYM6g7acl9qY5YGabFRNPhRo5fp5P47FNVRAbSXLP+IDVsGKBFYQN4yn3XA2rENe5iHonylvsIIFwuKUQiFJkSDDWVWbH1sVtE8E2fZxXuHFbz/mpyltlrOrcgu9tQ5KdULZ2oxsB4s+8Wb1SHqSK4rHzFuSJgxgC46HJWze+ZwvzW7eWEGl9M1/JoTqEVHuWEYgJ/kDbROGSszYUjKRDfvQIZvTonbqLUE9mHO0xUgrptq0/EwPttQlF+tKQhUaYzn7+WOy4mAKc6oJ1oIGWQbpwnQOTCjEc78lrt6I2yHeoRzdSPahn2vrdvUl3gHVzeqDNzMusmOlzdMVqk7wvkQHRrOda5XFTxechtSQ9YpEQHXyXxfk9ZIENWLx2azD8WHTUSisSov9YiI340uLkmHyr/omwsWk/DWEIJQcbpxLuhO5Q1VvNRq+GCilAQtOqcWeKCfUtXdX5xVIKUOmWE0d3Lhr6YT93bcqw2StPEWBWfFdNP0Dj/Arr9k9HjejkLm1o/d85+bBKTyrmmGI+1cZd6iH5XLQ0Gu3WR87szfyPTwWbJk/V0fMvPTKOkkwatTfOFEPYQNY08w5CluCWzlclNKmVcmAmbGgxyiT8TtHc=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
