sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        kpx80x+hhWEk6LCf10rnMy+aDeefVWxEXt2gI+F36T58AG4I/789yE6vnfa3vuf2OfxrPaXJLzx+lvj/LN6Sse5ok2bXEDEM65BAdgcXDBaTw4/Hn9OGbPlsJEjThjfWc4p8EcXkkpUq2H3inNPZbCBZ8c8uc1y/4tngnP2meHqTBQ34ZT0rrJlf6bTI+IocRP5AsblwYVJ4i2V94rCYmcgbda6XiN6A5L6Spz2CiQ9jmoktE4z4ZOg/+HHaQ10MEjFB7XxHn0+xuNG4v9jPN40JprNwa7NF0O1Bd1pM7rJ9iuzju/homv6agEXu/HfccHe7JjBm3kntDEkNrt6mY+XJZapgFis6zO3e3YRnM3N75WYHUGVgGQqp51AehxierZevBlqKuPSFPHxlmo6CAAhhV2fpmacux1wPAx5LcctOenMYC2iEGXwnzqBY2AVOHjR7A2s2D5x7hRpfVa31oWhv7Ohj1hRVqWwZ37nYWQMLtPxNDyYWGd3zvXnUIqqHdQynZhjHBDtBt7IkBaxRkQyybBNvdjQw9sUxPsdA6gSV7RNAObtxR/sgjGIYxWBtHd5IzKDkyGdj+cjFyrr/IxL0n5RTI3FacI1x/APyge6qEHYGHiHthRAT3UlX6Bp0jQIZVSScgnqwEvJArZzg7C0We2gIaEQ/AeSUHQMjLlU=
    - secure: >-
        ge2eqyDb8hQy28/kMb/gHRoRXoYu/cqHdkO2uHLcfaDNSlknOCVfkrgXTcWRyvjapAVBZVXByG8fiu5IB1x7Kt11Ig6O6NbzVkdF+cOLqVmNpTFRm1tnJ2NnLVPyDDBaLNdhTwkOkX6nMLU/87daPiW+vC4NGKRUM70dyDX12HGIkWAnEdRfV9ao87mabbCH0RdWwCyfG3HSHJOapal9+Bz7p9Ht8/1Yd+2QouboDYHTB3YlY9AnvIOEnzCNE00cRWZvMeuenPM/e8JJd96fIHlCXaRWATol+WnJv5kq3mryT5ee6HY6AAWbN0kg418CQQIZPT5ueSdg13Weg7QgZ2u5ao4UWmFu/datEhKFsD1qEucQqPeE+iq7A/Wur43f1iQoWCaA1ADffeU/Y4apii6dw05WSR8MM5RranP56zHB4C56LNQqPQODVnZIJvaTWA4JtBnVY3QkoETO9Fd+mSipjH5v0uXc5BYlu7SxJ6gMgVF6bf/dcOsT0lKKj2/MpbycDCm8+qtMb4N6x9zWhMdLueJXxtodlOfgPmcf2cbDYrassAyxW+TqFxsVOseSs0Y6/cQ1WnmVjdB+txA4XlVQ7eXxlvaJqk6afBQkQethMbLent1qUMtWQBnnkDqHBMlB8C0vNKKSC1b03aJ/tlUNjGEn2P9OkSJ6pFMLIcA=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
