sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        du+ZgxpDQZh7BCOop5zZT3KyHX/ZDVqqbq/1DM4wYR/+cx/2TOHobMSq3JCEq/roUSbF57kO8h+x6WjhXJdkoUgUq58T17rjeA6kACS79wJcDC0HAcfnHoAeUdznziPDVa4PvmiU65RAMAh7XR4R2fEqtuUaEI5aag8GPEe3rDFPASGQ4jtXFLNwMXBhGVUjoBlEF2e7v/6if9JEimPJP6oSGBfnxtQk3jhtVAdDAy1NufFp0n/bi++J+7FYpHo3hZq1zKT6WxhqeCqr5ISdw0prVXD+Ofj47Kz8AzznZUBufQsRiD4ZE4e74OYhYl0yz2tQl4FFARUvVg0pPTHL6YvND/6U8ZH+OlFp3hmVmPCiHnhV0/f9e+ZeAwFIDOEtiQJ8WbMjzT7GNY5wLKu7NDMGqMhhEKBvrtoroYCABCzY5yEB8tCeDMK91cDm8rct7Fs9/IoCcYdYeu9d6MRslsYRSLgU0umXPVe190a9imKT80RgvRQUqijSe5yh0SWzRFr+aACq4k6s6PTC3+B54dcwr/u/HXq6usB3WHckvfx4X1k4J23vCNBCiObmLsj+gjszHZeoyT+m7oqLdxTS2RO/uWCoNOXZqYlDsFhqLNqJUQG3FqBJttA5arNDf1/O4itz1ck8i7knqg1wIX4Pmvd+CsAZluaDhn9ecKCzxT8=
    - secure: >-
        BEatZQ3RbTGBloMI5//OwsIIhYX9gvXEkuvPAziQKMIXGQdffYEHg1A2bsFS93iiRr69wt9J8GiZI34CDLM5j10/EjFTBPKzzVZs7sxYzClOegleq9N3lWGCTvC3ikcCp/We3T5NnmgQGndrfhRPyFymv2aNnyNmv98rTRJr5bFj1yMAwaQGXniC4bc/jLroaGb2HanGWpg0aBtDQXX0yl/B8Dk0nkwCac69pSvLMvFnEeV1Eje1ueLYOclHhtzJNREoziiUjRu4M0ps6jwKGDYgjZqRftkb3qBRKuAfLke2hRb3oNaajRJE9P3Ufsm3UM8ZM6w/7qeq56AF5FGeWuIhbObYCCC9g+KdrkxCib8+eth+tcs8QWADXZuCEUkQZRC/rq82cRNaytXgB7bGWS42GIsV5+YMBLI0F+Uls++L5LdY+i2tpHIeNif7/VL84+CJzdReFwdfr4VHycrtQDXQNHIaLmWVxF7fC9Ut3Tdi6cnDUSfH+ckPhK3O+NNBTkXQ/3WLDAssx5Zzdq5x3OyjkUtTYSiZWGCpQebZZS4MmovyIxOhFlWuW4fj7bd9bHfzzcJ6C+yovCSArfIbFY9DKLOrD1GLRq4jXf+cEknEnpfk2nqg1IvpWMMwcF+sxCkZAzhsETXrnD1hpZwoW/UdAlecVSw8O2YUT3i0BKs=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
