sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        MNJFX0DnkFwhwsrAJyLwcnUPbfZfHhwy7H4qTc1m4St5sfVTDPm27ACfr8h6lP99vsvRdEjEAHmlElwYfhcvnmjr//8wnQo03HqeXCWdYw7g2yQviJFqk5U6rXOfiM8/x7lbFe7POadBAm/lI9lNfV0qF66phiBgxTxmCZoyAqD6BeDTVpZQSWyQYRi7bhZ3LuuAWMlq5MoeI+2oBWgFM++XVJQdQTuYSvBkApIoo6/AmKQSK0NyppQtu7ngU9MykWmrCsY5ER4LUs65g4FbnNEHxt842jM4CInkTh13i3HPCXV3V1TqB8pW6bR3ptH3SXaP8gKXrZqrSFxiWeNChOGknQGetg+mbXWJN2wzAVvRT7bUjZd0OKBNPbvfEzx2sN/Ea96N0lkrpMn9Z4efOI2n1Cy9N7UkcaJc1AGKziBBrmJ4CoJJdF92XLZlw1wexXWTVyQ/fLCGGK5LTbAtp6tfD5oCxQ4Y+rsv1XdOnYyj7OKAKF8/fPqmlgkp/EeZN3MgeUlF+UeumpHom4KPFjOCjToy+5aU3jqn09rv8U7o+GRc49WxiBRH7avIBNG16Dciwslxf1FQkBQ51I9MuC9KDPH2EbENu4cSd53Nqx3wkuPpP+ON1DKDEnHVQVVkuUBI2TNC/KKQvVsJGiyfIM3oLEbBs/pgQyFAZewCs/A=
    - secure: >-
        KRXyUKk59gMvaqYOAeyV6vvSf8599ib5JTXhUmrOAd+3IcDRDDW4Bx56zI22z3W3nEOcRK4L6E3QSjuXNuoumhCQOdVlfIsB6SGWnhJei8Y0EEa+87Dini9T+OtZE1bRfyA/rAx/7xfiqJzpNHE64mew3rd6TYEQxErlVmnkU7edEIXFIew0GOMmeIkOXbZ0ZljJ566AymPuBMlWlCdECOjdc/lXz46AcmBq8OisFnnR5DN5hZfgDZAUXaguFCMz+kpZICFmivBgpw9fj+oyg8P2Qgjx0b0W/UL5KLwe55RuwVg5R+BbuucsxNWMtclSp310dXhxD/b0eIwJASP5Kp+A1w+Tfn77SdFMYAY7U9glvZq0qlzWPqLct8n95gHtVXsPhfSHlZeallAQJO6WeGmRgLsq3NKcB+lWjuSDV7tM+G7W3Jw2naos/gkrM/7uxLsfyQT5+UtxkyeWrVMq8EMA/1f6b7zYseYJm18XMDWmHCQmONW/0dqNLgdDG+EMqry78wAV62bjax3Xko/6izqOIYLMBAJgEuh5x2ejh71buRRfsGgeHd0tmV4H7AYCU3MzCCy8jaMGjWeQoJ8sBJUKUA87oX0sqQixHS3gBhV1BsrjiSzFvCogDYUfn6H9j62PQz8bXkEhGyvH0VQwbx6Q0AES9o99kt1sf5it1t0=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
